repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.5
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/iterative/dvc
  rev: 3.38.0
  hooks:
    - id: dvc-pre-commit
      language_version: python3
      stages:
        - commit
    - id: dvc-pre-push
      additional_dependencies: ['.[gs]']
      language_version: python3
      stages:
        - push
    - always_run: true
      id: dvc-post-checkout
      language_version: python3
      stages:
        - post-checkout
