on:
  push:
    branches:
      - main
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    environment: 'cloud-function-deploy'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies with Poetry
      run: poetry install --no-dev

    - name: Generate requirements.txt
      run: poetry export -f requirements.txt --output requirements.txt --without-hashes

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'eng-interface-432120-c2@appspot.gserviceaccount.com'
        credentials_json: '${{ secrets.JSON_CREDENTIAL }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v2'
      with:
        name: 'data-processor-python'
        runtime: 'python312'
        project_id: 'eng-interface-432120-c2'
        entry_point: 'main'
